nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: ['*'] # authorize all origins request
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: []
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PATCH', 'DELETE']
    max_age: 3600
  paths:
    '^/api/': # the cors apply only on /api/
      allow_origin: ['http://localhost:3000', 'http://127.0.0.1:3000'] # authorize all origins request with this list
      allow_headers: ['Content-Type', 'Authorization']
      allow_methods: ['GET', 'OPTIONS', 'POST', 'PATCH', 'DELETE']
